export const ShowListActionConstants = {
  GET_ALL_SHOW_LISTS: 'GET_ALL_SHOW_LISTS',
  OPEN_MODAL: 'OPEN_MODAL',
  SEARCHED_VALUE: 'SEARCHED_VALUE',
  CLOSE_MODAL: 'CLOSE_MODAL',
  FETCH_TV_SHOW_LIST_DATA: 'FETCH_TV_SHOW_LIST_DATA',
  FETCH_ALL_TV_SHOW_LIST_DATA: 'FETCH_ALL_TV_SHOW_LIST_DATA',
  FETCH_TV_SHOW_LIST_ERROR: 'FETCH_TV_SHOW_LIST_ERROR',
  FETCH_TV_SHOW_DETAILS: 'FETCH_TV_SHOW_DETAILS',
  FETCH_SEARCH_DATA: 'FETCH_SEARCH_DATA',
};
