
export const LoginActionConstants = {
  POST_LOGIN_REQUEST: 'POST_LOGIN_REQUEST',
  SET_CURRENT_URL: 'SET_CURRENT_URL',
  CLEAR_CURRENT_URL: 'CLEAR_CURRENT_URL',
  SET_LOGIN_STATUS: 'SET_LOGIN_STATUS',
  CHECK_LOGIN: 'CHECK_LOGIN',
  UPDATE_USERNAME: 'UPDATE_USERNAME',
  LOGOUT_USER: 'LOGOUT_USER'
};